# Ідентифікатор проєкту в SonarQube (унікальний)
sonar.projectKey=Lab6
sonar.projectName=Lab6
sonar.projectVersion=1.0
# Шляхи до вихідного коду (можна вказати кілька, розділяючи комами)
# Ваші файли знаходяться в корені (index.html, CSS/, JS/), тому вказуємо '.'
sonar.sources=.
sonar.language=js
sonar.exclusions=**/node_modules/**, **/vendor/**, **/*.min.js
sonar.host.url=http://localhost:9000
sonar.login=sqp_cc2f07b5e9d3cddcc64e33737314845b3e21f254